"""Build labs/ch11/lab11b.ipynb — off-policy evaluation on the Tennessee Eastman simulator."""
import sys, pathlib
sys.path.insert(0, str(pathlib.Path(__file__).parent.parent))
from _nb import md, code, write_notebook  # noqa: E402

cells = [

md("""# Lab 11B — Off-Policy Evaluation on the Tennessee Eastman Simulator

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/sreent/causal-ai-for-smart-manufacturing/blob/main/labs/ch11/lab11b.ipynb)

**Companion to Lab 11A.** Lab 11A built a tabular MDP where we knew both the behaviour policy and the true value of the evaluation policy, then verified that IPS, SNIPS, and DR each recover that value within sampling error. **Lab 11B asks the same question on a continuous-state chemical-process simulator — the Tennessee Eastman (TE) plant.**

The setup is one a process-control engineer would recognise: someone logged a trajectory under the *current* operating recipe (a stochastic policy on a single intervention switch), a candidate *new* policy is proposed, and we have to estimate the candidate's expected reward *without* deploying it. The deliverable is the OPE estimate, the variance diagnostic (effective sample size), and a deploy-or-pilot decision.

**Dataset.** Two pre-simulated TE trajectories, generated by the vendored `tep2py` Fortran simulator (Downs & Vogel 1993) and committed in the repo:

- **Logged** (behaviour policy): 500 samples with the IDV(1) (\"A/C Feed Ratio\") disturbance toggled Bernoulli(0.5) each 3-minute step.
- **Candidate** (evaluation policy): 500 samples with IDV(1) = 0 always — i.e., never trigger the disturbance.

Because the simulator is the *true* generating process, the candidate trajectory's empirical return *is* the ground truth value of the evaluation policy. OPE on the logged data should recover it (within finite-sample noise). If it doesn't, the OPE estimator is biased — and that bias is the lesson."""),

md("""## What this lab is *not* doing

- **Building a sequential policy.** The evaluation policy is *stationary and deterministic* (always action = 0). Sequential / state-conditioned policies require the trajectory-product IPS form and substantially more data; we use the simpler per-step IPS suited to a stationary $\\pi_e$.
- **Running the live simulator.** The two trajectories are pre-generated. Re-simulation requires building the Fortran extension (see `labs/data/te_simulator/README.md`); the canonical CSVs cover this lab without it.
- **Tuning the reward.** The reward is a single, fixed quadratic deviation from a target reactor pressure. A real engineering analysis would use a multi-objective cost (pressure + temperature + quality + energy)."""),

code("""%pip install -q numpy pandas matplotlib scikit-learn"""),

code("""import os, sys, urllib.request, pathlib

# Pull the TE prep module from the repo on first run; it loads the committed CSVs.
PREP_PATH = pathlib.Path("/content/te_prep.py")
if not PREP_PATH.exists():
    urllib.request.urlretrieve(
        "https://raw.githubusercontent.com/sreent/causal-ai-for-smart-manufacturing/main/labs/data/te_prep.py",
        PREP_PATH,
    )
sys.path.insert(0, str(PREP_PATH.parent))

# The loader resolves CSVs relative to its own directory. Mirror the repo layout
# under /content so the loader finds them.
for name in ("te_logged.csv", "te_candidate.csv"):
    p = pathlib.Path("/content") / name
    if not p.exists():
        urllib.request.urlretrieve(
            f"https://raw.githubusercontent.com/sreent/causal-ai-for-smart-manufacturing/main/labs/data/{name}",
            p,
        )

from te_prep import load_te

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.ensemble import GradientBoostingRegressor

rng = np.random.default_rng(0)"""),

md("""## Part 1 — Load both trajectories"""),

code("""log  = load_te("logged")
cand = load_te("candidate")

print(f"Logged trajectory:    {log.shape}   action rate (IDV1=1): {log['action_idv1'].mean():.2f}")
print(f"Candidate trajectory: {cand.shape}   action rate (IDV1=1): {cand['action_idv1'].mean():.2f}")
print()
print("Logged columns (first 6):", list(log.columns)[:6], "...")"""),

md("""## Part 2 — Frame the OPE problem

OPE has its own shorthand. Before we deploy the estimators in Parts 3-5, here is the symbol table you should keep in view, with each row anchored to a specific column of the TE dataframe so the abstractions stay concrete.

| Symbol | Meaning | In our TE setup |
|--------|---------|-----------------|
| $s_t$ | State at step $t$ | The 41 XMEAS columns of the dataframe (process measurements) |
| $a_t$ | Action at step $t$ | `log['action_idv1'].iloc[t]` — 0 or 1 |
| $r_t$ | Reward at step $t$ | Computed from $s_t$: see formula below |
| $\\pi_b(a \\mid s)$ | *Behaviour* policy — the probability the logged data assigned action $a$ in state $s$ | $\\pi_b(0 \\mid s) = \\pi_b(1 \\mid s) = 0.5$ (the trajectory was generated with a fair-coin IDV(1)) |
| $\\pi_e(a \\mid s)$ | *Evaluation* policy — the policy we want to value | $\\pi_e(0 \\mid s) = 1$ always (never trigger IDV(1)) |
| $V(\\pi_e)$ | The number we are trying to estimate | $E_{\\pi_e}[r_t]$ — the per-step reward we would earn deploying $\\pi_e$ |

**Reward function.** $r_t = -(\\mathrm{XMEAS}(7)_t - 2700)^2 / 10^6$.

- `XMEAS(7)` is reactor pressure in kPa. *2700 kPa is the published normal-operating-point pressure for the Tennessee Eastman process* (Downs & Vogel 1993, Table 4) — it is the value the plant's controllers are nominally tuned to maintain.
- The negative-squared-deviation form turns "stay near target" into a maximisation objective for OPE. Dividing by $10^6$ scales the numbers to readable units (without the scale, a 100 kPa deviation gives $-10000$, which clutters the diagnostic tables).
- A real process-control analysis would use a multi-objective reward (pressure + temperature + product purity + energy); we use the single-objective form to keep the lab focused on OPE mechanics.

**Why this is a *causal* problem and not just a prediction problem.** The candidate policy *changes the action distribution*, which changes the *state* trajectory through the simulator's dynamics. Predicting reward under the candidate's action requires reasoning about a counterfactual world where IDV(1) is always 0, not interpolating from the world where it was a coin flip. That is what makes IPS / SNIPS / DR more than a re-weighted average."""),

code("""def reward(df, pressure_target=2700.0):
    return -((df["XMEAS(7)"].values - pressure_target) ** 2) / 1e6

r_log  = reward(log)
r_cand = reward(cand)

print(f"Logged  mean reward (mixed actions):     {r_log.mean():+.4f}")
print(f"Candidate mean reward (always off):       {r_cand.mean():+.4f}")
print()
print(f"Ground-truth V(pi_e) (from candidate):   {r_cand.mean():+.4f}")
print("This is the number OPE must recover from the logged data alone.")"""),

md("""## Part 3 — Per-step IPS

For a stationary, deterministic $\\pi_e$ and a stationary stochastic $\\pi_b$, per-step IPS is:

$$\\hat{V}_{IPS}(\\pi_e) = \\frac{1}{N} \\sum_{t=1}^{N} \\frac{\\pi_e(a_t \\mid s_t)}{\\pi_b(a_t \\mid s_t)} \\cdot r_t.$$

**Worked example, 4 rows.** Before unleashing this on 500 steps of TE, here is what the importance-weighting step does on a tiny sample, so the formula's mechanism is concrete:

| $t$ | $a_t$ | $\\pi_b(a_t\\mid s_t)$ | $\\pi_e(a_t \\mid s_t)$ | weight $w_t = \\pi_e/\\pi_b$ | $r_t$ | $w_t \\cdot r_t$ |
|----|-------|---------------------|---------------------|---------------------------|-------|-----------------|
| 1 | 0  | 0.5 | 1 (matches $\\pi_e$) | **2.0** | −0.10 | −0.20 |
| 2 | 1  | 0.5 | 0 (mismatches $\\pi_e$) | **0.0** | −0.40 | 0.00 |
| 3 | 0  | 0.5 | 1 | **2.0** | −0.05 | −0.10 |
| 4 | 1  | 0.5 | 0 | **0.0** | −0.60 | 0.00 |

Average $w_t \\cdot r_t$ across the 4 rows = $-0.075$. That is the IPS estimate $\\hat{V}_{IPS}$. Compare to the naive logged average $(-0.10 - 0.40 - 0.05 - 0.60)/4 = -0.2875$, which is biased toward the high-cost $a = 1$ steps the evaluation policy would never choose.

For our actual setup, $\\pi_e(0 \\mid s_t) = 1$ and $\\pi_b(0 \\mid s_t) = 0.5$, so the importance weight is $2$ on steps where $a_t = 0$ (the logged action matched the evaluation policy) and $0$ elsewhere — exactly the toy table above, just with 500 rows."""),

code("""def importance_weights(actions, pe_action=0, pb_prob=0.5):
    \"\"\"Per-step weight for a deterministic pi_e and a Bernoulli(pb_prob) pi_b.\"\"\"
    return np.where(actions == pe_action, 1.0 / pb_prob, 0.0)

w = importance_weights(log["action_idv1"].values, pe_action=0, pb_prob=0.5)
V_ips = float(np.mean(w * r_log))

# Kish's effective sample size: the equivalent number of unit-weight rows that
# would give the same variance as our actual weighted average. For weights w_t
# with mean 1, ESS = (Sum w)^2 / Sum(w^2). Low ESS means a few rows are doing
# most of the work, so the IPS estimate is high-variance regardless of N.
ess = (w.sum() ** 2) / (w ** 2).sum()
ess_frac = ess / len(w)

print(f"IPS estimate of V(pi_e):                 {V_ips:+.4f}")
print(f"Effective sample size (Kish):            {ess:.0f} of {len(w)}  ({100*ess_frac:.1f}%)")
print(f"Ground truth V(pi_e):                    {r_cand.mean():+.4f}")
print(f"IPS bias vs ground truth:                {V_ips - r_cand.mean():+.4f}")"""),

md("""**Interpreting the ESS number.**

- **ESS / N close to 1.0** — the weights are roughly uniform; every row contributes meaningfully; IPS variance is close to ordinary-average variance. This is the *favourable* regime.
- **ESS / N around 0.5** — some rows dominate but the estimate is still trustworthy; expect IPS variance ~2x naive variance.
- **ESS / N below ~0.1** — a small fraction of rows is doing most of the work. The IPS point estimate may be unbiased but its variance is huge, and finite-sample confidence intervals (when you compute them) will be wide.

In our run, ESS / N is around 50% because $\\pi_e$ matches $\\pi_b$'s most-likely action exactly half the time (Bernoulli(0.5) gives equal action share). On a more imbalanced behaviour policy — e.g., $\\pi_b(a=0) = 0.9$ when $\\pi_e(a=0) = 1$ — ESS / N would be much closer to 1; on the other extreme — $\\pi_b(a=0) = 0.1$ when $\\pi_e(a=0) = 1$ — ESS / N would crash near zero and IPS becomes useless.

**ESS is the most important OPE diagnostic.** A small bias against ground truth is forgivable if ESS / N > 0.25. A large bias with ESS / N < 0.10 means *the estimator literally has nothing to work with* — most logged rows had near-zero weight and got effectively dropped from the average."""),

md("""## Part 4 — Self-normalised IPS (SNIPS)

SNIPS divides by the sum of weights instead of $N$, trading a small bias for substantially lower variance:

$$\\hat{V}_{SNIPS}(\\pi_e) = \\frac{\\sum_t w_t \\cdot r_t}{\\sum_t w_t}.$$"""),

code("""V_snips = float(np.sum(w * r_log) / np.sum(w))

print(f"SNIPS estimate of V(pi_e):               {V_snips:+.4f}")
print(f"Ground truth V(pi_e):                    {r_cand.mean():+.4f}")
print(f"SNIPS bias vs ground truth:              {V_snips - r_cand.mean():+.4f}")"""),

md("""## Part 5 — Doubly robust (DR)

DR augments IPS with a fitted reward model $\\hat{r}(s, a)$. The variance reduction comes from using the model to predict the reward at the *evaluation* action even on steps where the logged action differed.

$$\\hat{V}_{DR}(\\pi_e) = \\frac{1}{N} \\sum_t \\left[\\hat{r}(s_t, \\pi_e(s_t)) + \\frac{\\pi_e(a_t \\mid s_t)}{\\pi_b(a_t \\mid s_t)} \\cdot (r_t - \\hat{r}(s_t, a_t))\\right].$$

If $\\hat{r}$ is exactly right, the IPS correction term has mean zero and DR equals the model-based estimate. If $\\pi_b$ is exactly right, the IPS correction recovers truth even under model misspecification. DR is consistent if *either* component is correct — the *doubly* in doubly robust."""),

code("""state_cols = [c for c in log.columns if c.startswith("XMEAS")]
S_log = log[state_cols].values
a_log = log["action_idv1"].values

# Fit r_hat(s, a) as a single regressor with a as a feature.
features = np.hstack([S_log, a_log.reshape(-1, 1)])
r_model = GradientBoostingRegressor(random_state=0)
r_model.fit(features, r_log)

# Direct model term: r_hat(s, pi_e(s)) — pi_e always picks a=0.
features_pe = np.hstack([S_log, np.zeros((len(S_log), 1))])
direct = r_model.predict(features_pe)

# IPS correction term.
r_hat_at_logged = r_model.predict(features)
correction = w * (r_log - r_hat_at_logged)

V_dr = float(np.mean(direct + correction))

print(f"DR estimate of V(pi_e):                  {V_dr:+.4f}")
print(f"Ground truth V(pi_e):                    {r_cand.mean():+.4f}")
print(f"DR bias vs ground truth:                 {V_dr - r_cand.mean():+.4f}")"""),

md("""## Part 5b — Double robustness in action

The claim "DR is consistent if *either* the reward model OR the propensity is correct" is easy to assert and hard to feel. Let's prove it by *breaking* the reward model on purpose and watching DR still recover the right number.

Three reward models, three DR runs, same propensity (which we know exactly):

1. **Correct.** Gradient boosting on $(s_t, a_t)$ — what we just fit.
2. **Misspecified.** A constant predictor that returns the marginal mean reward, ignoring $s_t$ and $a_t$ entirely.
3. **Zero.** A predictor that returns 0 everywhere (equivalent to plain IPS).

If DR's double-robustness story is real, all three should land near ground truth. If only the correct model gets close, DR isn't doing what we claim it does."""),

code("""# Common setup: the importance weights are the propensity component (known exactly).
# Only the reward model varies between runs.

def dr_estimate(direct_pe, r_hat_logged):
    \"\"\"Generic DR formula: direct model term + IPS correction.\"\"\"
    correction = w * (r_log - r_hat_logged)
    return float(np.mean(direct_pe + correction))

# Run 1 -- the correct reward model from Part 5 (re-using direct + correction).
V_dr_correct = V_dr

# Run 2 -- misspecified: constant predictor at the marginal mean.
mean_r = float(r_log.mean())
direct_const = np.full(len(S_log), mean_r)
V_dr_const = dr_estimate(direct_const, np.full(len(S_log), mean_r))

# Run 3 -- zero: ignores the reward model entirely (collapses DR to IPS).
direct_zero = np.zeros(len(S_log))
V_dr_zero = dr_estimate(direct_zero, np.zeros(len(S_log)))

truth = float(r_cand.mean())
table = pd.DataFrame({
    'reward model':       ['Correct (gradient boosting)',
                            'Misspecified (constant marginal mean)',
                            'Zero (collapses to IPS)'],
    'DR estimate':         [V_dr_correct, V_dr_const, V_dr_zero],
    'Bias vs ground truth': [V_dr_correct - truth,
                              V_dr_const - truth,
                              V_dr_zero - truth],
})
print(f'Ground truth V(pi_e): {truth:+.4f}')
print()
print(table.to_string(index=False, float_format=lambda x: f'{x:+.4f}'))"""),

md("""**Read the three rows.** All three DR estimates should be close to ground truth — within ~10% of each other — even though row 2 deliberately destroys the reward model's information and row 3 zeroes it out entirely. The reason is the IPS correction term: when $\\hat{r}$ is wrong, the residual $(r_t - \\hat{r}(s_t, a_t))$ contains the missing signal, and importance-weighting re-introduces it under $\\pi_e$.

If row 2 or row 3 *did* drift far from ground truth in your run, the propensity $\\pi_b$ was already mildly off (e.g., the logged actions weren't quite Bernoulli(0.5) due to a finite-sample blip), and DR has no good component to lean on.

**The same demonstration with broken propensity.** A parallel experiment — keep the correct reward model, but assume $\\pi_b(a=0) = 0.7$ instead of the true 0.5 — would show DR *still* close to ground truth, because the reward model would carry the load. That second experiment is left as an exercise; the lesson is symmetric."""),

md("""## Part 6 — Side-by-side comparison"""),

code("""table = pd.DataFrame({
    "estimator":  ["Naive logged mean", "IPS", "SNIPS", "DR", "Ground truth (candidate)"],
    "estimate":   [r_log.mean(), V_ips, V_snips, V_dr, r_cand.mean()],
    "bias":       [r_log.mean() - r_cand.mean(),
                   V_ips - r_cand.mean(),
                   V_snips - r_cand.mean(),
                   V_dr - r_cand.mean(),
                   0.0],
})
print(table.to_string(index=False, float_format=lambda x: f"{x:+.4f}"))"""),

md("""**Read the table.**

- **Naive logged mean** is what an analyst who ignored the policy difference would report — it averages reward under the *mixed* behaviour policy and is the wrong target.
- **IPS** is unbiased in expectation but high-variance when the ESS is small.
- **SNIPS** trades a small bias for sharper variance, useful when IPS has wide confidence intervals.
- **DR** uses the fitted reward model to cut variance further; if the model fits well, DR is the most efficient unbiased estimator.

The bias of each estimator relative to the ground-truth candidate return tells us whether OPE on the logged data can substitute for actually deploying the candidate."""),

md("""## Part 7 — Diagnostics: when to *not* trust OPE

OPE's reliability depends on three things, each with a simple diagnostic:

1. **Effective sample size.** ESS / N below ~10% means IPS variance is dominating any signal. Report SNIPS or DR instead, but also note that the candidate policy is reaching states the logged policy rarely visited.
2. **Reward-model fit.** Check the cross-validated MSE of $\\hat{r}$ on logged data. A bad fit means DR's variance-reduction promise is weak.
3. **Coverage.** If $\\pi_e$ chooses actions $\\pi_b$ never took in some states, no OPE estimator is valid there. For us this is trivially fine (both actions appear with prob 0.5), but state-conditioned $\\pi_e$ on real data often violates coverage."""),

code("""from sklearn.model_selection import cross_val_score

mse = -cross_val_score(GradientBoostingRegressor(random_state=0), features, r_log,
                       scoring="neg_mean_squared_error", cv=5).mean()
r_var = r_log.var()
print(f"Reward-model 5-fold MSE:    {mse:.6f}")
print(f"Variance of logged reward:  {r_var:.6f}")
print(f"R^2 of fit:                 {1 - mse/r_var:.3f}")
print()
print(f"ESS fraction (from Part 3): {100*ess_frac:.1f}%")"""),

md("""## Part 8 — Decision

Three bullets, the deployment-readiness report:

1. **Best OPE estimate of the candidate policy's expected per-step reward is the DR number** (read from Part 6's table); the bias against ground truth is the residual gap between OPE and a live pilot.

2. **The OPE estimate is trustworthy / fragile** based on the ESS fraction and reward-model $R^2$ from Part 7. ESS > 25% and $R^2$ > 0.5 is the comfortable regime; below either, treat the OPE number as an order-of-magnitude check rather than a deployment-grade estimate.

3. **If the bias of all three (IPS, SNIPS, DR) against ground truth is small, OPE is doing the job we hoped — substituting for a live pilot.** If the bias is large *and* the diagnostics looked fine, then either the reward function is poorly chosen, or the per-step IPS form is inadequate (the candidate policy's state distribution diverges from the logged distribution after a few steps, breaking the i.i.d. assumption per-step IPS makes)."""),

md("""## Reflection

**The TE simulator is its own oracle.** Most real OPE problems give us only the logged data; we have to take the OPE estimate on faith. Here we can directly compute $V(\\pi_e)$ from the candidate trajectory, and the comparison teaches us *which* OPE estimators are reliable in this regime.

**The biggest pitfall in industrial OPE is silent extrapolation.** When $\\pi_e$ takes the system into states $\\pi_b$ rarely visited, every OPE estimator extrapolates from the model implicit in the data — and extrapolation in chemical process control is where catastrophes live. The ESS diagnostic flags this in numbers; the chapter's Markov-coverage check (Lab 11A) flags it structurally. Run both."""),

md("""## What's next

Lab 12B uses the same TE simulator to build a *learned digital twin* — fit a structural model of the process from logged data, then plan a policy against the twin and validate against the real simulator. The twin step is what enables genuine causal reinforcement learning rather than purely observational OPE."""),
]

write_notebook(pathlib.Path(__file__).parent.parent / "ch11" / "lab11b.ipynb", cells)
print("Built lab11b.ipynb")
